import os
import re

# The correct favicon block (as generated by realfavicongenerator.net)
# Adjust the paths if your icons are in /favicon/ folder
new_favicon_block = '''    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#667eea">
    <meta name="msapplication-TileColor" content="#667eea">
    <meta name="theme-color" content="#667eea">'''

# Pattern to match all old favicon links (any <link> with href containing favicon)
old_pattern = r'<link[^>]*?href="[^"]*?favicon[^"]*?"[^>]*?>\s*'

def update_favicon_links(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    # Remove existing favicon related lines (including manifest link)
    # Also remove any old <meta> tags like msapplication-TileColor, theme-color
    content = re.sub(r'<link[^>]*?href="[^"]*?favicon[^"]*?"[^>]*?>\s*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'<link[^>]*?href="[^"]*?site\.webmanifest[^"]*?"[^>]*?>\s*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'<meta[^>]*?name="msapplication-TileColor"[^>]*?>\s*', '', content, flags=re.IGNORECASE)
    content = re.sub(r'<meta[^>]*?name="theme-color"[^>]*?>\s*', '', content, flags=re.IGNORECASE)
    
    # Insert new block after the first <meta charset> or after <head>
    # Find position after <head> or after charset meta
    head_tag = re.search(r'<head[^>]*>', content, re.IGNORECASE)
    if head_tag:
        pos = head_tag.end()
        content = content[:pos] + '\n' + new_favicon_block + '\n' + content[pos:]
    else:
        # fallback: insert at beginning
        content = '<head>\n' + new_favicon_block + '\n' + content
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"✅ Fixed: {filepath}")

def main():
    for root, dirs, files in os.walk('frontend'):
        for file in files:
            if file.endswith('.html'):
                path = os.path.join(root, file)
                update_favicon_links(path)
    print("🎉 All HTML files updated with correct favicon links.")

if __name__ == '__main__':
    main()